### ISSUE TITLE
You cannot modify the shared Matisse instance after it was first used

### ISSUE THREAD

**Issue by turganbekuly** [konoma/matisse#4]
After I logged out and tried to login I'm getting that issue

**Comment by frenetisch-applaudierend** [comment]
Hello NerdyNerd

Yes, that is intended. Once a Matisse instance is used, you cannot modify it anymore since those changes would not be reflected anyway.

I assume you setup Matisse somewhere after your login and therefore when logging in again you get this error. The easiest way to fix this is to move the configuration before the login is shown, e.g. in your application delegates application did start. Alternatively, if your Matisse configuration depends on what happens at login, you can use a custom Matisse instance which you recreate every time. This might need bigger changes in your code though.

Hope this helps!
